name: build

on:
  push:
    branches:
      - ci-bench
jobs:
  win32:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "windows-2022"
          - os: "windows-2025"
          - os: "windows-11-arm"
    env:
      WORKSPACE: ${{ github.workspace }}
    steps:
      - name: List some executables
        run: |
          file (get-command rustc).source
          file (get-command cmake).source
          file (get-command python).source
          file "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe"

      - name: Show disk layout
        run: |
          Get-Disk

      - name: Download DiskSpd
        run: |
          Invoke-WebRequest -Uri "https://github.com/microsoft/diskspd/releases/download/v2.2/DiskSpd.zip" -OutFile diskspd.zip
          Expand-Archive -Path diskspd.zip -DestinationPath diskspd

      - name: Benchmark workspace
        run: |
          $drive = (Get-Location).Path.Substring(0,1)
          Get-PSDrive -Name $drive
          .\diskspd\amd64\diskspd.exe -c10G -w50 -d10 ".\testfile.dat"

      - name: Benchmark C:\
        run: |
          Write-Host "Disk usage for C:\"
          Get-PSDrive -Name C
          .\diskspd\amd64\diskspd.exe -c10G -w50 -d10 "C:\testfile.dat"

      - name: Benchmark D:\ if exists
        run: |
          if (Test-Path "D:\") {
            Write-Host "Disk usage for D:\"
            Get-PSDrive -Name D
            .\diskspd\amd64\diskspd.exe -c10G -w50 -d10 "D:\testfile.dat"
          } else {
            Write-Host "D:\ drive not found, skipping."
          }

      - uses: samypr100/setup-dev-drive@v3
        with:
          drive-size: 12GB
          env-mapping: |
            WORKSPACE,{{ DEV_DRIVE_WORKSPACE }}

      - name: Benchmark Dev Drive
        working-directory: ${{ env.WORKSPACE }}
        run: |
          $drive = (Get-Location).Path.Substring(0,1)
          Get-PSDrive -Name $drive
          ${{ github.workspace }}\diskspd\amd64\diskspd.exe -c10G -w50 -d10 ".\testfile.dat"
