name: Cleanup caches

on:
  workflow_run:
    workflows: [build]
    types: [completed]

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh extension install actions/gh-actions-cache
          keys=$(gh actions-cache list -L 100 -R ${{ github.repository }} -B $BRANCH --sort last-used --order desc | cut -f 1)
          set +e
          echo $BRANCH
          echo $keys
          for key in "${keys[@]:1}"
          do
              echo $key
              gh actions-cache delete $key -R ${{ github.repository }} -B $BRANCH --confirm
          done
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH: ${{ github.event.workflow_run.head_branch }}
